In [93]:
import requests
import pandas as pd
from datetime import datetime, timedelta
import io

In [86]:
fecha_inicio = datetime.today() - timedelta(days=20)
fecha_fin = datetime.today() - timedelta(days=1)
fechas = pd.date_range(start=fecha_inicio, end=fecha_fin, freq='B')
fechas

DatetimeIndex(['2021-08-11 10:02:24.121499', '2021-08-12 10:02:24.121499',
               '2021-08-13 10:02:24.121499', '2021-08-16 10:02:24.121499',
               '2021-08-17 10:02:24.121499', '2021-08-18 10:02:24.121499',
               '2021-08-19 10:02:24.121499', '2021-08-20 10:02:24.121499',
               '2021-08-23 10:02:24.121499', '2021-08-24 10:02:24.121499',
               '2021-08-25 10:02:24.121499', '2021-08-26 10:02:24.121499',
               '2021-08-27 10:02:24.121499', '2021-08-30 10:02:24.121499'],
              dtype='datetime64[ns]', freq='B')

In [87]:
fechas = [fecha.strftime('%d/%m/%Y') for fecha in fechas]
fechas

['11/08/2021',
 '12/08/2021',
 '13/08/2021',
 '16/08/2021',
 '17/08/2021',
 '18/08/2021',
 '19/08/2021',
 '20/08/2021',
 '23/08/2021',
 '24/08/2021',
 '25/08/2021',
 '26/08/2021',
 '27/08/2021',
 '30/08/2021']

In [65]:
url= 'http://www.bcra.gov.ar/PublicacionesEstadisticas/Cotizaciones_por_fecha_2.asp'
post_data ={'pp1': '1', 'date2':fechas[3]}
response = requests.post(url, data=post_data)

In [66]:
df = pd.read_html(io.BytesIO(response.content), decimal=',', thousands='.')[0]
df

   MERCADO DE CAMBIOS - COTIZACIONES CIERRE VENDEDOR AL 19/08/2021  \
                                                            MONEDA
0                                  Bolívar Venezolano
1                                Cordoba Nicaraguense
2                                        Corona Checa
3                                       Corona Danesa
4                                      Corona Noruega
5                                        Corona Sueca
6                            Derecho Especial de Giro
7                                        Dinar Serbia
8                                   Dolar Australiano
9                                    Dolar Canadiense
10                                  Dolar de Singapur
11                               Dolar Estadounidense
12                                    Dolar Hong Kong
13                                  Dolar Neozelandes
14                          Dolar Referencia Com 3500
15                          Dong Vietnam (c/1.000 u.)
16                      Euro (Unidad Monetaria Europe
17                       Florin (Antillas Holandesas)
18                                       Franco Suizo
19                                  Guaraní Paraguayo
20                                    Libra Esterlina
21                                         Lira Turca
22                                  Nuevo Sol Peruano
23                                    Oro - Onza Troy
24                                               Peso
25                                     Peso Boliviano
26                                       Peso Chileno
27                                    Peso Colombiano
28                                      Peso Mexicano
29                                      Peso Uruguayo
30                                  Plata - Onza Troy
31                                   Rand Sudafricano
32                                      Real (Brasil)
33                                      Rublo (Rusia)
34                                      Rupia (India)
35                                    Shekel (Israel)
36                                        Yen (Japón)
37                                    Yuan- China CNY
38                           Yuan-China Off Shore CNH

                                            \
   TIPO DE PASE - EN DOLARES -(por unidad)
0                              0.000000245
1                                 0.028394
2                                 0.045784
3                                 0.157035
4                                 0.110643
5                                 0.113602
6                                  1.41758
7                                 0.009931
8                                   0.7151
9                                 0.780275
10                                0.732762
11                      ------------------
12                                0.128381
13                                  0.6829
14                      ------------------
15                                0.043833
16                                  1.1678
17                                  0.5576
18                                1.089325
19                                0.000144
20                                  1.3647
21                                0.117185
22                                 0.24322
23                                 1780.96
24                                 0.01028
25                                0.144789
26                                0.001268
27                                0.000258
28                                0.049569
29                                 0.02316
30                                 23.2328
31                                0.065646
32                                0.184771
33                                0.013453
34                                0.013468
35                                0.308024
36                                0.009108
37                                0.153967
38                                0.153851


   TIPO DE CAMBIO - MONEDA DE CURSO LEGAL - (por unidad)
0                                         0.000023827
1                                            2.762161
2                                            4.453866
3                                           15.276382
4                                           10.763324
5                                           11.051155
6                                          137.902182
7                                            0.966134
8                                           69.564928
9                                           75.905119
10                                          71.283066
11                                              97.28
12                                          12.488927
13                                          66.432512
14                                            97.2883
15                                           4.264048
16                                         113.603584
17                                          54.243337
18                                         105.969499
19                                           0.014021
20                                         132.758016
21                                          11.399777
22                                          23.660465
23                                 ------------------
24                                 ------------------
25                                          14.085078
26                                           0.123336
27                                           0.025137
28                                           4.822024
29                                           2.253025
30                                 ------------------
31                                           6.386052
32                                          17.974539
33                                           1.308737
34                                           1.310212
35                                          29.964577
36                                           0.886055
37                                          14.977906
38                                          14.966614

In [67]:
#Verificamos si tienen multi index
df.columns

MultiIndex([('MERCADO DE CAMBIOS - COTIZACIONES CIERRE VENDEDOR AL 19/08/2021', ...),
            ('MERCADO DE CAMBIOS - COTIZACIONES CIERRE VENDEDOR AL 19/08/2021', ...),
            ('MERCADO DE CAMBIOS - COTIZACIONES CIERRE VENDEDOR AL 19/08/2021', ...)],
           )

In [68]:
#Para formatear un poco la tabla y que podamos recopilar varias (deben tener el mismo nombre de columna)
#eliminamos el multi index
#Conviene revisar como queda luego para ver que no perdimos una parte relevante del nombre de las columnas
df.columns = df.columns.droplevel()
df.columns

Index(['MONEDA', 'TIPO DE PASE - EN DOLARES -(por unidad)',
       'TIPO DE CAMBIO - MONEDA DE CURSO LEGAL - (por unidad)'],
      dtype='object')

In [69]:
df

,MONEDA,TIPO DE PASE - EN DOLARES -(por unidad),TIPO DE CAMBIO - MONEDA DE CURSO LEGAL - (por unidad)
0,Bolívar Venezolano,0.000000245,0.000023827
1,Cordoba Nicaraguense,0.028394,2.762161
2,Corona Checa,0.045784,4.453866
3,Corona Danesa,0.157035,15.276382
4,Corona Noruega,0.110643,10.763324
5,Corona Sueca,0.113602,11.051155
6,Derecho Especial de Giro,1.41758,137.902182
7,Dinar Serbia,0.009931,0.966134
8,Dolar Australiano,0.7151,69.564928
9,Dolar Canadiense,0.780275,75.905119
10,Dolar de Singapur,0.732762,71.283066
11,Dolar Estadounidense,------------------,97.28
12,Dolar Hong Kong,0.128381,12.488927
13,Dolar Neozelandes,0.6829,66.432512
14,Dolar Referencia Com 3500,------------------,97.2883
15,Dong Vietnam (c/1.000 u.),0.043833,4.264048
16,Euro (Unidad Monetaria Europe,1.1678,113.603584
17,Florin (Antillas Holandesas),0.5576,54.243337
18,Franco Suizo,1.089325,105.969499
19,Guaraní Paraguayo,0.000144,0.014021
20,Libra Esterlina,1.3647,132.758016
21,Lira Turca,0.117185,11.399777
22,Nuevo Sol Peruano,0.24322,23.660465
23,Oro - Onza Troy,1780.96,------------------
24,Peso,0.01028,------------------
25,Peso Boliviano,0.144789,14.085078
26,Peso Chileno,0.001268,0.123336
27,Peso Colombiano,0.000258,0.025137
28,Peso Mexicano,0.049569,4.822024
29,Peso Uruguayo,0.02316,2.253025
30,Plata - Onza Troy,23.2328,------------------
31,Rand Sudafricano,0.065646,6.386052
32,Real (Brasil),0.184771,17.974539
33,Rublo (Rusia),0.013453,1.308737
34,Rupia (India),0.013468,1.310212
35,Shekel (Israel),0.308024,29.964577
36,Yen (Japón),0.009108,0.886055
37,Yuan- China CNY,0.153967,14.977906
38,Yuan-China Off Shore CNH,0.153851,14.966614

In [70]:
#En esta parte le vamos a agregar una columna con la fecha
df['Date'] = fechas[1]
df.set_index('Date', inplace=True)

df.head()

,MONEDA,TIPO DE PASE - EN DOLARES -(por unidad),TIPO DE CAMBIO - MONEDA DE CURSO LEGAL - (por unidad)
Date,,,
17/08/2021,Bolívar Venezolano,0.000000245,0.000023827
17/08/2021,Cordoba Nicaraguense,0.028394,2.762161
17/08/2021,Corona Checa,0.045784,4.453866
17/08/2021,Corona Danesa,0.157035,15.276382
17/08/2021,Corona Noruega,0.110643,10.763324

In [88]:
url= 'http://www.bcra.gov.ar/PublicacionesEstadisticas/Cotizaciones_por_fecha_2.asp'

#Lo hacemos iterativo
for indice, fecha in enumerate(fechas):
    #Definimos los datos que se envían como post data
    post_data ={'pp1': '1', 'date2':fecha}
    response = requests.post(url, data=post_data)
    
    df_temp = pd.read_html(io.BytesIO(response.content), decimal=',', thousands='.')[0]
    
    #Si la cantidad de filas no es nula, realizo todos los cambios
    if df_temp.shape[0] != 0:
    
        #Verificamos si hay mult index
        if df_temp.columns.nlevels == 2:
            df_temp.columns = df_temp.columns.droplevel()

        df_temp['Date'] = fecha
        
        #Hacemos el append
        if indice == 0:
            df = df_temp.copy()
        else:
            df = df.append(df_temp, ignore_index=True)            
    
    else:
        continue

In [90]:
df

,MONEDA,TIPO DE PASE - EN DOLARES -(por unidad),TIPO DE CAMBIO - MONEDA DE CURSO LEGAL - (por unidad),Date
0,Bolívar Venezolano,0.000000244,0.000023715,11/08/2021
1,Cordoba Nicaraguense,0.028211,2.737554,11/08/2021
2,Corona Checa,0.046265,4.489537,11/08/2021
3,Corona Danesa,0.157933,15.325816,11/08/2021
4,Corona Noruega,0.112901,10.955935,11/08/2021
...,...,...,...,...
502,Rupia (India),0.013647,1.333492,30/08/2021
503,Shekel (Israel),0.311061,30.393804,30/08/2021
504,Yen (Japón),0.009099,0.889081,30/08/2021
505,Yuan- China CNY,0.154638,15.109716,30/08/2021
506,Yuan-China Off Shore CNH,0.15471,15.116729,30/08/2021